import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useMutation } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { ArrowLeft, RotateCcw, Trash2 } from "lucide-react";
import { loadMistakes, clearMistakes, type StoredMistake } from "@/hooks/useProgress";
import { regenerateVariants, type QuizQuestion } from "@/lib/quiz.functions";
import { QuizRunner } from "@/components/quiz/QuizRunner";

export const Route = createFileRoute("/revise")({
  head: () => ({
    meta: [
      { title: "Revise Mistakes · Smart Practice | HBK Maths Quest" },
      { name: "description", content: "Re-practice every NCERT Maths question you got wrong, with fresh variants generated by HBK Mathy." },
    ],
  }),
  component: RevisePage,
});

function RevisePage() {
  const [mistakes, setMistakes] = useState<StoredMistake[]>([]);
  const [active, setActive] = useState<{
    grade: number;
    chapterId: number;
    chapterTitle: string;
    ids: string[];
    questions: QuizQuestion[];
  } | null>(null);

  const variants = useServerFn(regenerateVariants);

  useEffect(() => {
    setMistakes(loadMistakes());
  }, []);

  const mutation = useMutation({
    mutationFn: async (group: StoredMistake[]) => {
      const picked = group.slice(0, 10);
      const res = await variants({
        data: {
          grade: picked[0].grade,
          basis: picked.map((m) => ({
            prompt: m.question.prompt,
            answer: m.question.answer,
            type: m.question.type,
          })),
        },
      });
      const qs = res.questions as QuizQuestion[];
      const aligned = picked.slice(0, qs.length);
      return {
        grade: picked[0].grade,
        chapterId: picked[0].chapterId,
        chapterTitle: picked[0].chapterTitle,
        ids: aligned.map((m) => m.id),
        questions: qs,
      };
    },
    onSuccess: (payload) => setActive(payload),
  });

  // Group by chapter
  const groups = mistakes.reduce<Record<string, StoredMistake[]>>((acc, m) => {
    const key = `${m.grade}-${m.chapterId}`;
    (acc[key] ||= []).push(m);
    return acc;
  }, {});

  if (active) {
    return (
      <div className="mx-auto max-w-3xl px-4 py-6">
        <button
          onClick={() => {
            setActive(null);
            setMistakes(loadMistakes());
          }}
          className="text-muted-foreground hover:text-foreground mb-4 inline-flex items-center gap-1 text-sm font-semibold"
        >
          <ArrowLeft className="h-4 w-4" /> Back to mistakes
        </button>
        <QuizRunner
          questions={active.questions}
          title={`Revising · ${active.chapterTitle}`}
          subtitle={`Grade ${active.grade} · ${active.questions.length} questions`}
          context={{
            grade: active.grade,
            chapterId: active.chapterId,
            chapterTitle: active.chapterTitle,
            revisionMode: true,
            revisionIds: active.ids,
          }}
          onComplete={() => { /* outcomes tracked per question */ }}
        />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl px-4 py-6">
      <Link to="/" className="text-muted-foreground hover:text-foreground mb-4 inline-flex items-center gap-1 text-sm font-semibold">
        <ArrowLeft className="h-4 w-4" /> Home
      </Link>

      <div className="bg-gradient-hero shadow-glow mb-6 rounded-3xl p-6 text-white">
        <p className="text-xs font-semibold tracking-[0.2em] uppercase opacity-90">Smart Revision</p>
        <h1 className="text-3xl font-extrabold">Revise your mistakes</h1>
        <p className="mt-2 text-sm opacity-90">
          We save every question you get wrong. Practise them again with fresh variants — get it right twice and it disappears.
        </p>
      </div>

      {mistakes.length === 0 ? (
        <div className="bg-card shadow-card rounded-3xl p-10 text-center">
          <p className="text-2xl">🎉</p>
          <p className="mt-2 text-lg font-extrabold">No mistakes saved yet</p>
          <p className="text-muted-foreground mt-1 text-sm">
            Play a chapter quiz — any question you miss will land here for revision.
          </p>
          <Link
            to="/"
            className="bg-primary text-primary-foreground mt-5 inline-flex rounded-xl px-5 py-3 font-bold"
          >
            Pick a grade
          </Link>
        </div>
      ) : (
        <div className="space-y-3">
          {Object.values(groups).map((group) => {
            const first = group[0];
            return (
              <div key={first.id} className="bg-card shadow-card rounded-2xl p-5">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <p className="text-muted-foreground text-[10px] font-bold tracking-[0.18em] uppercase">
                      Grade {first.grade}
                    </p>
                    <p className="font-extrabold">{first.chapterTitle}</p>
                    <p className="text-muted-foreground mt-1 text-sm">
                      {group.length} saved mistake{group.length === 1 ? "" : "s"}
                    </p>
                  </div>
                  <button
                    onClick={() => mutation.mutate(group)}
                    disabled={mutation.isPending}
                    className="bg-primary text-primary-foreground hover:bg-primary/90 inline-flex items-center gap-2 rounded-xl px-4 py-2 font-bold disabled:opacity-50"
                  >
                    <RotateCcw className="h-4 w-4" />
                    {mutation.isPending ? "Loading…" : `Revise ${Math.min(10, group.length)}`}
                  </button>
                </div>
              </div>
            );
          })}

          {mutation.isError && (
            <p className="text-destructive text-sm font-semibold">{(mutation.error as Error).message}</p>
          )}

          <button
            onClick={() => {
              if (confirm("Clear all saved mistakes?")) {
                clearMistakes();
                setMistakes([]);
              }
            }}
            className="text-muted-foreground hover:text-destructive mt-4 inline-flex items-center gap-1 text-sm font-semibold"
          >
            <Trash2 className="h-4 w-4" /> Clear mistake bank
          </button>
        </div>
      )}
    </div>
  );
}
