/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksheetRouteImport } from './routes/worksheet'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as ReviseRouteImport } from './routes/revise'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MockRouteImport } from './routes/mock'
import { Route as MisconceptionsRouteImport } from './routes/misconceptions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GradeGradeIdRouteImport } from './routes/grade.$gradeId'
import { Route as BillingSuccessRouteImport } from './routes/billing.success'
import { Route as FlashcardsGradeIdChapterIdRouteImport } from './routes/flashcards.$gradeId.$chapterId'
import { Route as GradeGradeIdChapterChapterIdRouteImport } from './routes/grade.$gradeId.chapter.$chapterId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WorksheetRoute = WorksheetRouteImport.update({
  id: '/worksheet',
  path: '/worksheet',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviseRoute = ReviseRouteImport.update({
  id: '/revise',
  path: '/revise',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MockRoute = MockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => rootRouteImport,
} as any)
const MisconceptionsRoute = MisconceptionsRouteImport.update({
  id: '/misconceptions',
  path: '/misconceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradeGradeIdRoute = GradeGradeIdRouteImport.update({
  id: '/grade/$gradeId',
  path: '/grade/$gradeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsGradeIdChapterIdRoute =
  FlashcardsGradeIdChapterIdRouteImport.update({
    id: '/flashcards/$gradeId/$chapterId',
    path: '/flashcards/$gradeId/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GradeGradeIdChapterChapterIdRoute =
  GradeGradeIdChapterChapterIdRouteImport.update({
    id: '/chapter/$chapterId',
    path: '/chapter/$chapterId',
    getParentRoute: () => GradeGradeIdRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/misconceptions': typeof MisconceptionsRoute
  '/mock': typeof MockRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/pricing': typeof PricingRoute
  '/progress': typeof ProgressRoute
  '/revise': typeof ReviseRoute
  '/tutor': typeof TutorRoute
  '/worksheet': typeof WorksheetRoute
  '/billing/success': typeof BillingSuccessRoute
  '/grade/$gradeId': typeof GradeGradeIdRouteWithChildren
  '/flashcards/$gradeId/$chapterId': typeof FlashcardsGradeIdChapterIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/grade/$gradeId/chapter/$chapterId': typeof GradeGradeIdChapterChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/misconceptions': typeof MisconceptionsRoute
  '/mock': typeof MockRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/pricing': typeof PricingRoute
  '/progress': typeof ProgressRoute
  '/revise': typeof ReviseRoute
  '/tutor': typeof TutorRoute
  '/worksheet': typeof WorksheetRoute
  '/billing/success': typeof BillingSuccessRoute
  '/grade/$gradeId': typeof GradeGradeIdRouteWithChildren
  '/flashcards/$gradeId/$chapterId': typeof FlashcardsGradeIdChapterIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/grade/$gradeId/chapter/$chapterId': typeof GradeGradeIdChapterChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/misconceptions': typeof MisconceptionsRoute
  '/mock': typeof MockRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/pricing': typeof PricingRoute
  '/progress': typeof ProgressRoute
  '/revise': typeof ReviseRoute
  '/tutor': typeof TutorRoute
  '/worksheet': typeof WorksheetRoute
  '/billing/success': typeof BillingSuccessRoute
  '/grade/$gradeId': typeof GradeGradeIdRouteWithChildren
  '/flashcards/$gradeId/$chapterId': typeof FlashcardsGradeIdChapterIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/grade/$gradeId/chapter/$chapterId': typeof GradeGradeIdChapterChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom'
    | '/daily'
    | '/dashboard'
    | '/login'
    | '/misconceptions'
    | '/mock'
    | '/onboarding'
    | '/parent'
    | '/pricing'
    | '/progress'
    | '/revise'
    | '/tutor'
    | '/worksheet'
    | '/billing/success'
    | '/grade/$gradeId'
    | '/flashcards/$gradeId/$chapterId'
    | '/api/public/payments/webhook'
    | '/grade/$gradeId/chapter/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom'
    | '/daily'
    | '/dashboard'
    | '/login'
    | '/misconceptions'
    | '/mock'
    | '/onboarding'
    | '/parent'
    | '/pricing'
    | '/progress'
    | '/revise'
    | '/tutor'
    | '/worksheet'
    | '/billing/success'
    | '/grade/$gradeId'
    | '/flashcards/$gradeId/$chapterId'
    | '/api/public/payments/webhook'
    | '/grade/$gradeId/chapter/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/custom'
    | '/daily'
    | '/dashboard'
    | '/login'
    | '/misconceptions'
    | '/mock'
    | '/onboarding'
    | '/parent'
    | '/pricing'
    | '/progress'
    | '/revise'
    | '/tutor'
    | '/worksheet'
    | '/billing/success'
    | '/grade/$gradeId'
    | '/flashcards/$gradeId/$chapterId'
    | '/api/public/payments/webhook'
    | '/grade/$gradeId/chapter/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomRoute: typeof CustomRoute
  DailyRoute: typeof DailyRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MisconceptionsRoute: typeof MisconceptionsRoute
  MockRoute: typeof MockRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentRoute: typeof ParentRoute
  PricingRoute: typeof PricingRoute
  ProgressRoute: typeof ProgressRoute
  ReviseRoute: typeof ReviseRoute
  TutorRoute: typeof TutorRoute
  WorksheetRoute: typeof WorksheetRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  GradeGradeIdRoute: typeof GradeGradeIdRouteWithChildren
  FlashcardsGradeIdChapterIdRoute: typeof FlashcardsGradeIdChapterIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worksheet': {
      id: '/worksheet'
      path: '/worksheet'
      fullPath: '/worksheet'
      preLoaderRoute: typeof WorksheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revise': {
      id: '/revise'
      path: '/revise'
      fullPath: '/revise'
      preLoaderRoute: typeof ReviseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock': {
      id: '/mock'
      path: '/mock'
      fullPath: '/mock'
      preLoaderRoute: typeof MockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/misconceptions': {
      id: '/misconceptions'
      path: '/misconceptions'
      fullPath: '/misconceptions'
      preLoaderRoute: typeof MisconceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade/$gradeId': {
      id: '/grade/$gradeId'
      path: '/grade/$gradeId'
      fullPath: '/grade/$gradeId'
      preLoaderRoute: typeof GradeGradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/$gradeId/$chapterId': {
      id: '/flashcards/$gradeId/$chapterId'
      path: '/flashcards/$gradeId/$chapterId'
      fullPath: '/flashcards/$gradeId/$chapterId'
      preLoaderRoute: typeof FlashcardsGradeIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade/$gradeId/chapter/$chapterId': {
      id: '/grade/$gradeId/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/grade/$gradeId/chapter/$chapterId'
      preLoaderRoute: typeof GradeGradeIdChapterChapterIdRouteImport
      parentRoute: typeof GradeGradeIdRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GradeGradeIdRouteChildren {
  GradeGradeIdChapterChapterIdRoute: typeof GradeGradeIdChapterChapterIdRoute
}

const GradeGradeIdRouteChildren: GradeGradeIdRouteChildren = {
  GradeGradeIdChapterChapterIdRoute: GradeGradeIdChapterChapterIdRoute,
}

const GradeGradeIdRouteWithChildren = GradeGradeIdRoute._addFileChildren(
  GradeGradeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomRoute: CustomRoute,
  DailyRoute: DailyRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MisconceptionsRoute: MisconceptionsRoute,
  MockRoute: MockRoute,
  OnboardingRoute: OnboardingRoute,
  ParentRoute: ParentRoute,
  PricingRoute: PricingRoute,
  ProgressRoute: ProgressRoute,
  ReviseRoute: ReviseRoute,
  TutorRoute: TutorRoute,
  WorksheetRoute: WorksheetRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  GradeGradeIdRoute: GradeGradeIdRouteWithChildren,
  FlashcardsGradeIdChapterIdRoute: FlashcardsGradeIdChapterIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
